from model.db import DB
from py.helper import calculate_md5_hash


class URL(DB):
    TABLE = 'urls'
    COLS_IGNORE = ['id', 'created_at', 'updated_at']

    def __init__(self):
        params = {
            'table_name': self.TABLE
        }
        super().__init__(**params)

    def insert(self, data):
        # public_id column generated by generate_public_id('urls'::text, 8) function so no need to insert
        data['destination_link_hash'] = calculate_md5_hash(data['destination_link'])
        return super().insert(data)

    def get_by_destination_link_hash(self, destination_link):
        destination_link_hash = calculate_md5_hash(destination_link)
        return self.get_by_field('destination_link_hash', destination_link_hash)
