from model.model import Model

class URL_Alias(Model):
    TABLE = 'url_aliases'
    COLS_IGNORE = ['id']
    COLS_EXE_FCT = ['public_id']
    PUBLIC_ID_LENGTH = 5

    def __init__(self):
        params = {
            'table_name': self.TABLE
        }
        super().__init__(**params)

    def insert(self, data):
        # public_id column generated by generate_public_id('urls'::text, 5) function so no need to insert
        if 'public_id' not in data or data['public_id'] is None or data['public_id'] == '':
            data['public_id'] = f"generate_public_id('{self.TABLE}'::text, {self.PUBLIC_ID_LENGTH})"
        return super().insert(data)

    def get_by_url_id_cookie_uuid(self, url_id, cookie_uuid):
        conditions = [
            {
                'column': 'url_id',
                'value': url_id
            },
            {
                'column': 'cookie_uuid',
                'value': cookie_uuid
            }
        ]
        return self.get_by_conditions(conditions)

